language: node_js
node_js:
- '5'
sudo: required
services:
- docker
addons:
  ssh_known_hosts:
  - 162.243.218.96
branches:
  only:
  - travis-chindow
  - master
after_success:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t bablot/chindow .
- docker push bablot/chindow
- chmod 600 ./tmp_keys/key
- node_modules/.bin/shipit staging deploy

before_install:
- openssl aes-256-cbc -K $encrypted_9d6bd9f30265_key -iv $encrypted_9d6bd9f30265_iv
  -in key.enc -out ./tmp_keys/key -d
env:
  global:
  - secure: qSpeEcetoBvzNBEQG4eIxGHPxw5ePL6taKto03p9i8N3o80xR3xyKzmVQFRXC/bE2OaEvCEanTwjJRZbObSmzyZPAX4nq1k59I2uqG27Jwb+rObMirHkYZdG1Rkz+J7gEEBu6fkhPDFpsMJAgbiiQ5eFOSExUTzHA6f4mxPLwVOfxhK8kZJctSPE+/xuUoJPTS/yTRbIY+iueDTIVYvZpj2lilKRuhjvQScvshlqAcXAi7hDl1y/oP1TdFgdgZIuoMLu83CyaiowD7k+51eWahnnQqNtBLrksh8d2sqyyDr+am3b8qowbt6R5oTLD2BNUeiZYK2VjJfG91l2Sc7qWMhm0iFb+aPnA8I/CyubQGkQZwibrIPzFpuf6ZnKfIWX5ZRBn80HiAETFVe6ltOI1pbpI9YHa/bJ6Uyy/x9Q/sOcS3TDDVzEKqa9mVYHqksxX10x9BeLB5E0H92pV/1fw4Xd6tsljMp5khmcKZArT4zwkEnrvPHZlLXAqlQtFTjalLKRShx5tLSs8JzLiWReNIPJfitSZqg1wVJoxyxtbdnsJpKH4tgw0C9l/JOQTrnOtcBohibiOmfWKhDdItt6tCrPyVP/o8DfwN7/Fffucm+E7ebC19+JHMuu7wOTVYIGJQUjPeLCScJem001smVlmW/C1nipOU+pn6e72pcShDw=
  - secure: XFlYgx3W62YZhWPk7ER23JDKa+8ThEY7gf/jbgqZkB1YdD+amuwMxRRYj4f+8paJAa5emE890G6oQ1NfRxm13V/oBU6cYGcv/3VgCAU4uh/3XuuvwPdsSEJlPaDYIVd+wLe/HRox7+RQH54mgqIfGqhfrQhGxBE3Pnl1ZCFYkS6Ik2apI2jqe+AAA5T1DQFucj6YsdZd08bZUnj8/rMiDwRWK4Pvlx+85Y7d9wuKxlbFjxMiWgB32hGcHaxdT6ReEBk/NVVkxlB7wv/mqz+w/FgmJzUT4vX13/scU539X91Dhfern3fmLkxrNvF1zgod7vcwTyPFn3Sqm7R58hbh+rxIXGELqykDrOdiMhYt6w4HyAEn71+oKVLpKLnd+zOZrQ7G0gg+qB3BinI/Vgb+adOlyLTuQKTyUL5YaV8eXu0bJj86I2d6P7mL0BD2FxM5ZFanEbQg37n6AuBel2csVBRoDNbMwtXCXNP5dhV5VcyhJF7puTVPdiOtsy4NX3yMtKUWWL5A74TS1+kagzXeCx9e1/y9g58eXA6AA6+QNWqKkc5xH10T9oXQHkFuQn5HbS4OVTkpmFD0bSCd9xl2RPD7kNa38Y167jpjTgDLF5Kk2FPa3JuC1ZFb/5K0zPiMUW0BjjiORgK51CMWZqzVNX9mRNpKapAtJ4Q+Qfx3Js4=
  - secure: k6A6uSEnxk+8g+2YCqbYHmHCLo96uRz7k0ayXGZxAaRiHUbh3wtElOS+4lpGyc+qs0tHKZZ1nRR4c72JYqPU5D3ijsSFSh+LY+71970yJ6OUy2CakFN+1Tj8JFjLeCmcfMSxZmX5LO4b0r2rMcwA7yRCQb1V5QCPRoMoM7u7Ize1dLHcGHNDutnAsMkYsYmdlcfjxEj6QtJcgmJRix3KGHQN+YndCdMMlWTkTArVo3AkoSwWZneoJ1BozGCSOQv86XFQ/Q19+7w+WqbrubZKMfJdRqaczrkxFF0NdsaBah57mTa8QDU4kQf5pC+mM/rfhQrOibS8/9h2LYdkQK/hCxOv9iSbdp4znD7TYJK70yucm8vqRY/Zko9jWg5DXHu5EuL6rs1k7BNIT66iPmdLrCpsWW2Hq0Xlht+u5HMbzWs2fsjejiodeZ5EtbTKaxWHdy4u0SMV2KtRX0vMVJAzqIOtpsrLdMU5nQfLLGT+9ZtdgOUCWlVPQiKewHAK1XEs7ju+jGBsONx7+NVbqD09ulHsWxtPVNg8UAyRN9OJCb5Tew3pEgyDERwKgeQ6fDO1K+02lI/GOlcK73nAmLvXooQ91saRXiwCe3RPAZutq6fMfKmn25gnz1yWbUH7r5sbzwUNHfV3qLkMh+E7KKHD9ys+MDcJLcc94e9s77Uu5uc=
